services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kui
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_NAME: r4zt_wrqTRuT7W2NJsB_GA
    ports:
      - 8084:8080
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
